name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "I recognise that you have posted an issue, but given that it's a stupid-ass issue, I've elected to ignore it."
        pr-message: "Have you tried turning it off and on again?"
